# Generated by Django 2.0.6 on 2018-07-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicion',
            name='estado',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('REJECTED', 'Rejected')], default='PENDIENTE', max_length=25),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='estado',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('REJECTED', 'Rejected')], default='PENDIENTE', max_length=25),
        ),
        migrations.AlterField(
            model_name='participantecomposicion',
            name='estado',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('REJECTED', 'Rejected')], default='PENDIENTE', max_length=25),
        ),
        migrations.AlterField(
            model_name='participantepistason',
            name='estado',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('REJECTED', 'Rejected')], default='PENDIENTE', max_length=25),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('REJECTED', 'Rejected')], default='PENDIENTE', max_length=25),
        ),
        migrations.AlterField(
            model_name='personagrupo',
            name='estado',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('REJECTED', 'Rejected')], default='PENDIENTE', max_length=25),
        ),
        migrations.AlterField(
            model_name='pistason',
            name='estado',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('REJECTED', 'Rejected')], default='PENDIENTE', max_length=25),
        ),
        migrations.AlterField(
            model_name='serie',
            name='estado',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('REJECTED', 'Rejected')], default='PENDIENTE', max_length=25),
        ),
    ]
