# Generated by Django 2.0.6 on 2018-07-22 14:29

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension, TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0002_auto_20180709_0024'),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension()

    ]
