# Generated by Django 2.0.6 on 2018-08-12 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poet', '0006_auto_20180722_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalComposicion',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('nom', models.TextField()),
                ('nom_alt', models.TextField(blank=True, null=True)),
                ('fecha_pub', models.CharField(blank=True, max_length=10, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('REJECTED', 'Rejected')], default='PENDIENTE', max_length=25)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cargador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='poet.Participante')),
                ('composicion_orig', models.ForeignKey(blank=True, db_column='composicion_orig', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='poet.Composicion')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mod', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='poet.Usuario')),
            ],
            options={
                'verbose_name': 'historical composicion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
