# Generated by Django 2.1.2 on 2018-10-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0011_rename_columns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalentity',
            old_name='comments',
            new_name='commentary',
        ),
        migrations.RenameField(
            model_name='historicalentitytoentityrel',
            old_name='comment',
            new_name='commentary',
        ),
        migrations.RenameField(
            model_name='historicalentitytoworkrel',
            old_name='comments',
            new_name='commentary',
        ),
        migrations.RenameField(
            model_name='historicalwork',
            old_name='comments',
            new_name='commentary',
        ),
        migrations.RenameField(
            model_name='historicalworktoworkrel',
            old_name='comments',
            new_name='commentary',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='from_date_end',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='to_date_end',
        ),
        migrations.RemoveField(
            model_name='entitytoentityrel',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='entitytoentityrel',
            name='from_date_end',
        ),
        migrations.RemoveField(
            model_name='entitytoentityrel',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='entitytoentityrel',
            name='to_date_end',
        ),
        migrations.RemoveField(
            model_name='historicalentity',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='historicalentity',
            name='from_date_end',
        ),
        migrations.RemoveField(
            model_name='historicalentity',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='historicalentity',
            name='to_date_end',
        ),
        migrations.RemoveField(
            model_name='historicalentitytoentityrel',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='historicalentitytoentityrel',
            name='from_date_end',
        ),
        migrations.RemoveField(
            model_name='historicalentitytoentityrel',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='historicalentitytoentityrel',
            name='to_date_end',
        ),
        migrations.RemoveField(
            model_name='historicalwork',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='historicalwork',
            name='to_date',
        ),
        migrations.RemoveField(
            model_name='work',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='work',
            name='to_date',
        ),
        migrations.AlterField(
            model_name='entitytoentityrel',
            name='from_entity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ee_from_model', to='poet.Entity'),
        ),
        migrations.AlterField(
            model_name='entitytoentityrel',
            name='to_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ee_to_model', to='poet.Entity'),
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='from_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ew_from_model', to='poet.Entity'),
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='to_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ew_to_model', to='poet.Work'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='from_entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='poet.Entity'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='to_work',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='poet.Work'),
        ),
        migrations.AlterField(
            model_name='worktoworkrel',
            name='from_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ww_from_model', to='poet.Work'),
        ),
        migrations.AlterField(
            model_name='worktoworkrel',
            name='to_work_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ww_to_model', to='poet.Work'),
        ),
    ]
