# Generated by Django 2.1.2 on 2018-11-14 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_old_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.TextField(choices=[('Persona', 'Persona'), ('Grupo', 'Grupo'), ('Organización', 'Organización'), ('Festival', 'Festival'), ('Universidad', 'Universidad'), ('Colectivo', 'Colectivo'), ('Estación radiofónica', 'Estación radiofónica'), ('Educación e investigación', 'Educación e investigación'), ('Archivo sonoro', 'Archivo sonoro'), ('Servicios de streaming', 'Servicios de streaming'), ('Museo', 'Museo'), ('Editorial', 'Editorial'), ('Sello discográfico', 'Sello discográfico'), ('Centro cultural', 'Centro cultural'), ('Banda musical', 'Banda musical')], db_column='entity_type', default='Persona'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='release_state',
            field=models.TextField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE'),
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='role',
            field=models.TextField(choices=[('Composición', 'Composición'), ('Lectura en voz alta', 'Lectura en voz alta'), ('Interpretación musical', 'Interpretación musical'), ('Ingeniería de sonido', 'Ingeniería de sonido'), ('Producción', 'Producción'), ('Dirección', 'Dirección'), ('Post-producción', 'Post-producción'), ('Auxiliar de sonido', 'Auxiliar de sonido'), ('Contribuidor', 'Contribuidor'), ('Publicador', 'Publicador'), ('Traducción', 'Publicador')], default='Lectura en voz alta'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='entity_type',
            field=models.TextField(choices=[('Persona', 'Persona'), ('Grupo', 'Grupo'), ('Organización', 'Organización'), ('Festival', 'Festival'), ('Universidad', 'Universidad'), ('Colectivo', 'Colectivo'), ('Estación radiofónica', 'Estación radiofónica'), ('Educación e investigación', 'Educación e investigación'), ('Archivo sonoro', 'Archivo sonoro'), ('Servicios de streaming', 'Servicios de streaming'), ('Museo', 'Museo'), ('Editorial', 'Editorial'), ('Sello discográfico', 'Sello discográfico'), ('Centro cultural', 'Centro cultural'), ('Banda musical', 'Banda musical')], db_column='entity_type', default='Persona'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='release_state',
            field=models.TextField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='from_entity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Entity'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='role',
            field=models.TextField(choices=[('Composición', 'Composición'), ('Lectura en voz alta', 'Lectura en voz alta'), ('Interpretación musical', 'Interpretación musical'), ('Ingeniería de sonido', 'Ingeniería de sonido'), ('Producción', 'Producción'), ('Dirección', 'Dirección'), ('Post-producción', 'Post-producción'), ('Auxiliar de sonido', 'Auxiliar de sonido'), ('Contribuidor', 'Contribuidor'), ('Publicador', 'Publicador'), ('Traducción', 'Publicador')], default='Lectura en voz alta'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='to_work',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Work'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='release_state',
            field=models.TextField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='work_type',
            field=models.TextField(choices=[('Serie', 'Series'), ('Pista Son', 'Recording')], db_column='work_type', default='Pista Son'),
        ),
        migrations.AlterField(
            model_name='work',
            name='release_state',
            field=models.TextField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.TextField(choices=[('Serie', 'Series'), ('Pista Son', 'Recording')], db_column='work_type', default='Pista Son'),
        ),
        migrations.AlterField(
            model_name='worktoworkrel',
            name='to_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ww_to_model', to='app.Work'),
        ),
        migrations.DeleteModel(
            name='EntityToWorkRole',
        ),
        migrations.DeleteModel(
            name='EntityType',
        ),
        migrations.DeleteModel(
            name='ReleaseState',
        ),
        migrations.DeleteModel(
            name='WorkType',
        ),
    ]
