# Generated by Django 2.1.2 on 2018-11-28 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181126_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitytoentityrel',
            old_name='role',
            new_name='relationship',
        ),
        migrations.RenameField(
            model_name='entitytoworkrel',
            old_name='role',
            new_name='relationship',
        ),
        migrations.RenameField(
            model_name='historicalentitytoentityrel',
            old_name='role',
            new_name='relationship',
        ),
        migrations.RenameField(
            model_name='historicalentitytoworkrel',
            old_name='role',
            new_name='relationship',
        ),
        migrations.RenameField(
            model_name='historicalworktoworkrel',
            old_name='order',
            new_name='track_order',
        ),
        migrations.RenameField(
            model_name='worktoworkrel',
            old_name='order',
            new_name='track_order',
        ),
        migrations.RenameField(
            model_name='historicalworktoworkrel',
            old_name='role',
            new_name='relationship'
        ),
        migrations.RenameField(
            model_name='worktoworkrel',
            old_name='role',
            new_name='relationship'
        ),
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='end_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entitytoentityrel',
            name='end_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='entitytoentityrel',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalentity',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalentity',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicalentity',
            name='end_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalentity',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalentity',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalentitytoentityrel',
            name='end_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalentitytoentityrel',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='date_contributed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='date_digitalized',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='date_published',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='date_recorded',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='media_of_origin',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Cinta', 'Cinta'), ('CD', 'CD'), ('Vinilo', 'Vinilo')], default='Digital', max_length=20),
        ),
        migrations.AddField(
            model_name='work',
            name='date_contributed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='date_digitalized',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='date_published',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='date_recorded',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='work',
            name='media_of_origin',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Cinta', 'Cinta'), ('CD', 'CD'), ('Vinilo', 'Vinilo')], default='Digital', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='work_type',
            field=models.TextField(choices=[('Serie', 'Serie'), ('Pista son', 'Pista son')], db_column='work_type', default='Pista son'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.TextField(choices=[('Serie', 'Serie'), ('Pista son', 'Pista son')], db_column='work_type', default='Pista son'),
        ),
    ]
