# Generated by Django 2.1.2 on 2018-12-09 14:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0021_change_work_type_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='alt_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('Persona', 'Persona'), ('Grupo', 'Grupo'), ('Organización', 'Organización'), ('Festival', 'Festival'), ('Universidad', 'Universidad'), ('Colectivo', 'Colectivo'), ('Estación radiofónica', 'Estación radiofónica'), ('Educación e investigación', 'Educación e investigación'), ('Archivo sonoro', 'Archivo sonoro'), ('Servicios de streaming', 'Servicios de streaming'), ('Museo', 'Museo'), ('Editorial', 'Editorial'), ('Sello discográfico', 'Sello discográfico'), ('Centro cultural', 'Centro cultural'), ('Banda musical', 'Banda musical')], db_column='entity_type', default='Persona', max_length=128),
        ),
        migrations.AlterField(
            model_name='entity',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='release_state',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE', max_length=32),
        ),
        migrations.AlterField(
            model_name='entitytoentityrel',
            name='relationship',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='relationship',
            field=models.CharField(choices=[('Composición', 'Composición'), ('Lectura en voz alta', 'Lectura en voz alta'), ('Interpretación musical', 'Interpretación musical'), ('Ingeniería de sonido', 'Ingeniería de sonido'), ('Producción', 'Producción'), ('Dirección', 'Dirección'), ('Post-producción', 'Post-producción'), ('Auxiliar de sonido', 'Auxiliar de sonido'), ('Contribuidor', 'Contribuidor'), ('Publicador', 'Publicador'), ('Traducción', 'Publicador')], default='Lectura en voz alta', max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='alt_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='entity_type',
            field=models.CharField(choices=[('Persona', 'Persona'), ('Grupo', 'Grupo'), ('Organización', 'Organización'), ('Festival', 'Festival'), ('Universidad', 'Universidad'), ('Colectivo', 'Colectivo'), ('Estación radiofónica', 'Estación radiofónica'), ('Educación e investigación', 'Educación e investigación'), ('Archivo sonoro', 'Archivo sonoro'), ('Servicios de streaming', 'Servicios de streaming'), ('Museo', 'Museo'), ('Editorial', 'Editorial'), ('Sello discográfico', 'Sello discográfico'), ('Centro cultural', 'Centro cultural'), ('Banda musical', 'Banda musical')], db_column='entity_type', default='Persona', max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='release_state',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalentitytoentityrel',
            name='relationship',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='relationship',
            field=models.CharField(choices=[('Composición', 'Composición'), ('Lectura en voz alta', 'Lectura en voz alta'), ('Interpretación musical', 'Interpretación musical'), ('Ingeniería de sonido', 'Ingeniería de sonido'), ('Producción', 'Producción'), ('Dirección', 'Dirección'), ('Post-producción', 'Post-producción'), ('Auxiliar de sonido', 'Auxiliar de sonido'), ('Contribuidor', 'Contribuidor'), ('Publicador', 'Publicador'), ('Traducción', 'Publicador')], default='Lectura en voz alta', max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='alt_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='copyright',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='copyright_country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='file_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('images', 'Image')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='path_to_file',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='release_state',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='work_type',
            field=models.CharField(choices=[('Serie', 'Serie'), ('Pista son', 'Pista son')], db_column='work_type', default='Pista son', max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalworktoworkrel',
            name='relationship',
            field=models.CharField(blank=True, choices=[('series<contains>album', 'Is the series which contains this album.'), ('series<contains>recording', 'Is the series which contains this track.'), ('series<influenced>recording', 'Is a series which influenced this track.')], default='series<contains>recording', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='alt_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='copyright',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='copyright_country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='file_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('images', 'Image')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='work',
            name='path_to_file',
            field=models.FileField(null=True, upload_to='audio/upload_date=%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='work',
            name='release_state',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE', max_length=32),
        ),
        migrations.AlterField(
            model_name='work',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('Serie', 'Serie'), ('Pista son', 'Pista son')], db_column='work_type', default='Pista son', max_length=128),
        ),
        migrations.AlterField(
            model_name='worktoworkrel',
            name='relationship',
            field=models.CharField(blank=True, choices=[('series<contains>album', 'Is the series which contains this album.'), ('series<contains>recording', 'Is the series which contains this track.'), ('series<influenced>recording', 'Is a series which influenced this track.')], default='series<contains>recording', max_length=256, null=True),
        ),
    ]
