# Generated by Django 2.1.2 on 2018-12-09 15:04

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0022_filefield_and_charfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkCollection',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('work_name', models.CharField(blank=True, max_length=256)),
                ('image', models.TextField(max_length=100, null=True)),
                ('commentary', models.TextField(blank=True, null=True)),
                ('additional_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('release_state', models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE', max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical work collection',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(blank=True, max_length=256)),
                ('image', models.ImageField(null=True, upload_to='images/upload_date=%Y%m%d')),
                ('commentary', models.TextField(blank=True, null=True)),
                ('additional_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('release_state', models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE', max_length=32)),
            ],
            options={
                'db_table': 'poet_work_collection',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='track_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='track_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='in_collection',
            field=models.ForeignKey(blank=True, db_column='in_collection', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.WorkCollection'),
        ),
        migrations.AddField(
            model_name='work',
            name='in_collection',
            field=models.ForeignKey(db_column='in_collection', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.WorkCollection'),
        ),

        migrations.RunSQL("""
        INSERT INTO poet_work_collection (id, work_name, image, additional_data, commentary, release_state ) 
        SELECT id, full_name, path_to_file, additional_data, commentary, release_state 
        FROM poet_work WHERE work_type = 'Serie';
        """),

        migrations.RunSQL("""
        UPDATE poet_work pw SET track_number = track_order, in_collection = rel.from_work
            FROM poet_work_to_work_rel rel 
            WHERE rel.to_work = pw.id 
            AND rel.relationship = 'series<contains>recording'
        """)
    ]
