# Generated by Django 2.1.2 on 2018-12-09 15:26

from django.db import migrations, models
import django.contrib.postgres.fields
import app.controllers.util as u
from django.conf import settings
import os


def generate_waveform_peaks(apps, schema_editor):
    works = apps.get_model('app', 'Work')
    for work in works.objects.all():
        if not work.waveform_peaks:
            fname = work.audio.name
            filepath = os.path.join(settings.MEDIA_ROOT, fname)
            codec = u.get_extension(fname)
            work.waveform_peaks = u.get_peaks_from_audio_path(filepath, codec)
            work.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_clean_recursive_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwork',
            name='work_type',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_type',
        ),
        migrations.AlterField(
            model_name='work',
            name='path_to_file',
            field=models.FileField(max_length=512, upload_to='audio/upload_date=%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='path_to_file',
            field=models.TextField(max_length=512),
        ),

        migrations.RenameField(
            model_name='historicalwork',
            old_name='path_to_file',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='path_to_file',
            new_name='audio',
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='waveform_peaks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list,
                                                            editable=False, size=None),
        ),
        migrations.AddField(
            model_name='work',
            name='waveform_peaks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list,
                                                            editable=False, size=None),
        ),

        migrations.RunPython(generate_waveform_peaks),

        migrations.RunSQL("""
        CREATE OR REPLACE FUNCTION join_words(word1 text, word2 text) RETURNS text AS $body$
        BEGIN
          RETURN array_to_string(
            ARRAY[nullif(trim(word1), ''), nullif(trim(word2), '')], ' - '
          );
        END;
        $body$
        LANGUAGE plpgsql
        IMMUTABLE;
        """)

    ]
