# Generated by Django 2.1.2 on 2018-12-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_from_poet_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalworkcollection',
            old_name='work_name',
            new_name='collection_name',
        ),
        migrations.RenameField(
            model_name='workcollection',
            old_name='work_name',
            new_name='collection_name',
        ),
    ]
