# Generated by Django 2.1.4 on 2018-12-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_split_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytoworkrel',
            name='instrument',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='historicalentitytoworkrel',
            name='instrument',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='historicalworkcollection',
            name='origin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='workcollection',
            name='origin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),

        migrations.RunSQL("""
        UPDATE poet_entity_to_work_rel SET instrument = nullif(trim(additional_data->>'Instrumento'::text), '');
        """),

        migrations.RunSQL("""
        UPDATE poet_work_collection SET origin = nullif(trim(additional_data->>'Giro'::text), '');
        """),

        migrations.RunSQL("""
        UPDATE poet_entity_to_entity_rel SET start_date = nullif(trim(additional_data->>'Inicio'::text), ''),
        end_date = nullif(trim(additional_data->>'Finalización'::text), '');
    """),
    ]
