# Generated by Django 2.1.4 on 2018-12-30 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_move_additional_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitytoworkrel',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='historicalentitytoworkrel',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='historicalwork',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='historicalworkcollection',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='work',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='workcollection',
            name='additional_data',
        ),
    ]
