# Generated by Django 2.1.2 on 2019-01-03 21:51

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_delete_additional_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwork',
            name='copyright_date',
        ),
        migrations.RemoveField(
            model_name='work',
            name='copyright_date',
        ),
        migrations.AlterField(
            model_name='entity',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Additional Data'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='alt_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Alternative name'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Additional commentary'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='end_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Active to'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('Persona', 'Persona'), ('Grupo', 'Grupo'), ('Organización', 'Organización'), ('Festival', 'Festival'), ('Universidad', 'Universidad'), ('Colectivo', 'Colectivo'), ('Estación radiofónica', 'Estación radiofónica'), ('Educación e investigación', 'Educación e investigación'), ('Archivo sonoro', 'Archivo sonoro'), ('Servicios de streaming', 'Servicios de streaming'), ('Museo', 'Museo'), ('Editorial', 'Editorial'), ('Sello discográfico', 'Sello discográfico'), ('Centro cultural', 'Centro cultural'), ('Banda musical', 'Banda musical')], db_column='entity_type', default='Persona', max_length=128, verbose_name='Entity Type'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='release_state',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE', max_length=32, verbose_name='State of Publication'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='self_relation',
            field=models.ManyToManyField(blank=True, through='app.EntityToEntityRel', to='app.Entity', verbose_name='Relationship to recordings'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Active from'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='work_relation',
            field=models.ManyToManyField(blank=True, through='app.EntityToWorkRel', to='app.Work', verbose_name='Relationship to other entities'),
        ),
        migrations.AlterField(
            model_name='entitytoentityrel',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Additional commentary'),
        ),
        migrations.AlterField(
            model_name='entitytoentityrel',
            name='contains',
            field=models.BooleanField(default=False, help_text='Does the from entity contain the other e.g. ', verbose_name='Contains'),
        ),
        migrations.AlterField(
            model_name='entitytoentityrel',
            name='end_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date ended'),
        ),
        migrations.AlterField(
            model_name='entitytoentityrel',
            name='from_entity',
            field=models.ForeignKey(db_column='from_entity', help_text='The entity that this relationship is coming from.', on_delete=django.db.models.deletion.CASCADE, related_name='ee_from_model', to='app.Entity', verbose_name='From Entity'),
        ),
        migrations.AlterField(
            model_name='entitytoentityrel',
            name='relationship',
            field=models.CharField(blank=True, help_text='Type of relationship between the two entities', max_length=256, null=True, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='entitytoentityrel',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date started'),
        ),
        migrations.AlterField(
            model_name='entitytoentityrel',
            name='to_entity',
            field=models.ForeignKey(db_column='to_entity', help_text='The entity that this relationship is going to.', on_delete=django.db.models.deletion.CASCADE, related_name='ee_to_model', to='app.Entity', verbose_name='To Entity'),
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Additional commentary'),
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='from_entity',
            field=models.ForeignKey(db_column='from_entity', on_delete=django.db.models.deletion.CASCADE, related_name='ew_from_model', to='app.Entity', verbose_name='From entity'),
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='instrument',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='relationship',
            field=models.CharField(choices=[('Composición', 'Composición'), ('Lectura en voz alta', 'Lectura en voz alta'), ('Interpretación musical', 'Interpretación musical'), ('Ingeniería de sonido', 'Ingeniería de sonido'), ('Producción', 'Producción'), ('Dirección', 'Dirección'), ('Post-producción', 'Post-producción'), ('Auxiliar de sonido', 'Auxiliar de sonido'), ('Contribuidor', 'Contribuidor'), ('Publicador', 'Publicador'), ('Traducción', 'Publicador')], default='Lectura en voz alta', max_length=256, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='to_work',
            field=models.ForeignKey(db_column='to_work', on_delete=django.db.models.deletion.CASCADE, related_name='ew_to_model', to='app.Work', verbose_name='To recording'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Additional Data'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='alt_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Alternative name'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Additional commentary'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='end_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Active to'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='entity_type',
            field=models.CharField(choices=[('Persona', 'Persona'), ('Grupo', 'Grupo'), ('Organización', 'Organización'), ('Festival', 'Festival'), ('Universidad', 'Universidad'), ('Colectivo', 'Colectivo'), ('Estación radiofónica', 'Estación radiofónica'), ('Educación e investigación', 'Educación e investigación'), ('Archivo sonoro', 'Archivo sonoro'), ('Servicios de streaming', 'Servicios de streaming'), ('Museo', 'Museo'), ('Editorial', 'Editorial'), ('Sello discográfico', 'Sello discográfico'), ('Centro cultural', 'Centro cultural'), ('Banda musical', 'Banda musical')], db_column='entity_type', default='Persona', max_length=128, verbose_name='Entity Type'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='release_state',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE', max_length=32, verbose_name='State of Publication'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Active from'),
        ),
        migrations.AlterField(
            model_name='historicalentity',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoentityrel',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Additional commentary'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoentityrel',
            name='contains',
            field=models.BooleanField(default=False, help_text='Does the from entity contain the other e.g. ', verbose_name='Contains'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoentityrel',
            name='end_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date ended'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoentityrel',
            name='relationship',
            field=models.CharField(blank=True, help_text='Type of relationship between the two entities', max_length=256, null=True, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoentityrel',
            name='start_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date started'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Additional commentary'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='instrument',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='relationship',
            field=models.CharField(choices=[('Composición', 'Composición'), ('Lectura en voz alta', 'Lectura en voz alta'), ('Interpretación musical', 'Interpretación musical'), ('Ingeniería de sonido', 'Ingeniería de sonido'), ('Producción', 'Producción'), ('Dirección', 'Dirección'), ('Post-producción', 'Post-producción'), ('Auxiliar de sonido', 'Auxiliar de sonido'), ('Contribuidor', 'Contribuidor'), ('Publicador', 'Publicador'), ('Traducción', 'Publicador')], default='Lectura en voz alta', max_length=256, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='alt_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Alternative title'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='audio',
            field=models.TextField(max_length=512, verbose_name='Recording'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Additional commentary'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='copyright',
            field=models.CharField(choices=[('(C) Copyright', '(C) Copyright'), ('(CC BY) Creative Commons Atribución', '(CC BY) Creative Commons Atribución'), ('(CC BY-SA) Creative Commons Atribución-CompartirIgual', '(CC BY-SA) Creative Commons Atribución-CompartirIgual'), ('(CC BY-NC) Creative Commons Atribución-NoComercial', '(CC BY-NC) Creative Commons Atribución-NoComercial'), ('(CC BY-NC-SA) Creative Commons Atribución-NoComercial-CompartirIgual', '(CC BY-NC-SA) Creative Commons Atribución-NoComercial-CompartirIgual'), ('(CC BY-NC-ND) Creative Commons Atribución-NoComercial-SinDerivadas', '(CC BY-NC-ND) Creative Commons Atribución-NoComercial-SinDerivadas'), ('(CC0) Sin derechos reservados', '(CC0) Sin derechos reservados'), ('(GPL) Licencia pública general GNU', '(GPL) Licencia pública general GNU'), ('(LGPL) Licencia pública menos general GNU', '(LGPL) Licencia pública menos general GNU'), ('Dominio público', 'Dominio público'), ('Patente', 'Patente'), ('Por confirmar', 'Por confirmar'), ('Copyleft', 'Copyleft'), ('(CC BY-ND) Creative Commons Atribución-SinDerivadas', '(CC BY-ND) Creative Commons Atribución-SinDerivadas')], default='(CC BY) Creative Commons Atribución', max_length=128, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='copyright_country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Country of License'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='date_contributed',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date contributed'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='date_digitalized',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date digitized'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='date_published',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='date_recorded',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date recorded'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, null=True, size=None, verbose_name='Languages Spoken'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='media_of_origin',
            field=models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Cinta', 'Cinta'), ('CD', 'CD'), ('Vinilo', 'Vinilo')], default='Digital', max_length=20, null=True, verbose_name='Media of origin'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='poetry_text',
            field=models.TextField(blank=True, null=True, verbose_name='Composition text'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='release_state',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE', max_length=32, verbose_name='State of Publication'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='track_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Track number in that collection'),
        ),
        migrations.AlterField(
            model_name='historicalworkcollection',
            name='collection_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Collection title'),
        ),
        migrations.AlterField(
            model_name='historicalworkcollection',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Additional commentary'),
        ),
        migrations.AlterField(
            model_name='historicalworkcollection',
            name='image',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Album art'),
        ),
        migrations.AlterField(
            model_name='historicalworkcollection',
            name='origin',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='historicalworkcollection',
            name='release_state',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE', max_length=32, verbose_name='State of Publication'),
        ),
        migrations.AlterField(
            model_name='work',
            name='alt_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Alternative title'),
        ),
        migrations.AlterField(
            model_name='work',
            name='audio',
            field=models.FileField(max_length=512, upload_to='audio/upload_date=%Y%m%d', verbose_name='Recording'),
        ),
        migrations.AlterField(
            model_name='work',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='work',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Additional commentary'),
        ),
        migrations.AlterField(
            model_name='work',
            name='copyright',
            field=models.CharField(choices=[('(C) Copyright', '(C) Copyright'), ('(CC BY) Creative Commons Atribución', '(CC BY) Creative Commons Atribución'), ('(CC BY-SA) Creative Commons Atribución-CompartirIgual', '(CC BY-SA) Creative Commons Atribución-CompartirIgual'), ('(CC BY-NC) Creative Commons Atribución-NoComercial', '(CC BY-NC) Creative Commons Atribución-NoComercial'), ('(CC BY-NC-SA) Creative Commons Atribución-NoComercial-CompartirIgual', '(CC BY-NC-SA) Creative Commons Atribución-NoComercial-CompartirIgual'), ('(CC BY-NC-ND) Creative Commons Atribución-NoComercial-SinDerivadas', '(CC BY-NC-ND) Creative Commons Atribución-NoComercial-SinDerivadas'), ('(CC0) Sin derechos reservados', '(CC0) Sin derechos reservados'), ('(GPL) Licencia pública general GNU', '(GPL) Licencia pública general GNU'), ('(LGPL) Licencia pública menos general GNU', '(LGPL) Licencia pública menos general GNU'), ('Dominio público', 'Dominio público'), ('Patente', 'Patente'), ('Por confirmar', 'Por confirmar'), ('Copyleft', 'Copyleft'), ('(CC BY-ND) Creative Commons Atribución-SinDerivadas', '(CC BY-ND) Creative Commons Atribución-SinDerivadas')], default='(CC BY) Creative Commons Atribución', max_length=128, verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='work',
            name='copyright_country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Country of License'),
        ),
        migrations.AlterField(
            model_name='work',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date_contributed',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date contributed'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date_digitalized',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date digitized'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date_published',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date published'),
        ),
        migrations.AlterField(
            model_name='work',
            name='date_recorded',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Date recorded'),
        ),
        migrations.AlterField(
            model_name='work',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='work',
            name='in_collection',
            field=models.ForeignKey(db_column='in_collection', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.WorkCollection', verbose_name='Collection that this recording is a part of'),
        ),
        migrations.AlterField(
            model_name='work',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, null=True, size=None, verbose_name='Languages Spoken'),
        ),
        migrations.AlterField(
            model_name='work',
            name='media_of_origin',
            field=models.CharField(blank=True, choices=[('Digital', 'Digital'), ('Cinta', 'Cinta'), ('CD', 'CD'), ('Vinilo', 'Vinilo')], default='Digital', max_length=20, null=True, verbose_name='Media of origin'),
        ),
        migrations.AlterField(
            model_name='work',
            name='poetry_text',
            field=models.TextField(blank=True, null=True, verbose_name='Composition text'),
        ),
        migrations.AlterField(
            model_name='work',
            name='release_state',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE', max_length=32, verbose_name='State of Publication'),
        ),
        migrations.AlterField(
            model_name='work',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='work',
            name='track_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Track number in that collection'),
        ),
        migrations.AlterField(
            model_name='workcollection',
            name='collection_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Collection title'),
        ),
        migrations.AlterField(
            model_name='workcollection',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='Additional commentary'),
        ),
        migrations.AlterField(
            model_name='workcollection',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='images/upload_date=%Y%m%d', verbose_name='Album art'),
        ),
        migrations.AlterField(
            model_name='workcollection',
            name='origin',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='workcollection',
            name='release_state',
            field=models.CharField(choices=[('PUBLICADO', 'Published'), ('DEPOSITAR', 'Deposited'), ('PENDIENTE', 'Pending'), ('RECHAZADO', 'Rejected')], db_column='release_state', default='PENDIENTE', max_length=32, verbose_name='State of Publication'),
        ),

        migrations.AlterModelOptions(
            name='entity',
            options={'managed': True, 'verbose_name': 'Entity'},
        ),
        migrations.AlterModelOptions(
            name='entitytoentityrel',
            options={'managed': True, 'verbose_name': 'Entity to entity relationship'},
        ),
        migrations.AlterModelOptions(
            name='entitytoworkrel',
            options={'managed': True, 'verbose_name': 'Entity to recording relationship'},
        ),
        migrations.AlterModelOptions(
            name='historicalentity',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'),
                     'verbose_name': 'historical Entity'},
        ),
        migrations.AlterModelOptions(
            name='historicalentitytoentityrel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'),
                     'verbose_name': 'historical Entity to entity relationship'},
        ),
        migrations.AlterModelOptions(
            name='historicalentitytoworkrel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'),
                     'verbose_name': 'historical Entity to recording relationship'},
        ),
        migrations.AlterModelOptions(
            name='historicalwork',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'),
                     'verbose_name': 'historical Recording'},
        ),
        migrations.AlterModelOptions(
            name='historicalworkcollection',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'),
                     'verbose_name': 'historical Recording collection'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'managed': True, 'verbose_name': 'Recording'},
        ),
        migrations.AlterModelOptions(
            name='workcollection',
            options={'managed': True, 'verbose_name': 'Recording collection'},
        ),
        migrations.AlterField(
            model_name='entitytoentityrel',
            name='contains',
            field=models.BooleanField(default=False,
                                      help_text='Does the from entity contain the other e.g. collective contains individual',
                                      verbose_name='Contains'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoentityrel',
            name='contains',
            field=models.BooleanField(default=False,
                                      help_text='Does the from entity contain the other e.g. collective contains individual',
                                      verbose_name='Contains'),
        ),
    ]
