# Generated by Django 2.1.4 on 2019-01-09 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='historicalentity',
            name='email_address',
        ),
        migrations.AddField(
            model_name='historicalwork',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='External URL'),
        ),
        migrations.AddField(
            model_name='historicalworkcollection',
            name='album_art_design',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Album art design'),
        ),
        migrations.AddField(
            model_name='work',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='External URL'),
        ),
        migrations.AddField(
            model_name='workcollection',
            name='album_art_design',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Album art design'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoentityrel',
            name='from_entity',
            field=models.ForeignKey(blank=True, db_column='from_entity', db_constraint=False, help_text='The entity that this relationship is coming from.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Entity', verbose_name='From Entity'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoentityrel',
            name='to_entity',
            field=models.ForeignKey(blank=True, db_column='to_entity', db_constraint=False, help_text='The entity that this relationship is going to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Entity', verbose_name='To Entity'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='from_entity',
            field=models.ForeignKey(blank=True, db_column='from_entity', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Entity', verbose_name='From entity'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='to_work',
            field=models.ForeignKey(blank=True, db_column='to_work', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.Work', verbose_name='To recording'),
        ),
        migrations.AlterField(
            model_name='historicalwork',
            name='in_collection',
            field=models.ForeignKey(blank=True, db_column='in_collection', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.WorkCollection', verbose_name='Collection that this recording is a part of'),
        ),
    ]
