# Generated by Django 2.1.4 on 2019-01-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_requested_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'managed': True, 'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='entitytoentityrel',
            options={'managed': True, 'verbose_name': 'Entity to entity relationship', 'verbose_name_plural': 'Entity to entity relationships'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'managed': True, 'verbose_name': 'Recording', 'verbose_name_plural': 'Recordings'},
        ),
        migrations.AlterModelOptions(
            name='workcollection',
            options={'managed': True, 'verbose_name': 'Recording collection', 'verbose_name_plural': 'Recording collections'},
        ),
        migrations.AlterModelOptions(
            name='entitytoworkrel',
            options={'managed': True, 'verbose_name': 'Entity to recording relationship', 'verbose_name_plural': 'Entity to recording relationships'},
        ),
        migrations.AlterModelOptions(
            name='entitytoworkrel',
            options={'managed': True, 'verbose_name': 'Entity to recording relationship',
                     'verbose_name_plural': 'Entity to recording relationships'},
        ),
    ]
