# Generated by Django 2.1.7 on 2019-04-29 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_model_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitytoentityrel',
            options={'managed': True, 'verbose_name': 'Affiliation', 'verbose_name_plural': 'Affiliations'},
        ),
        migrations.AlterModelOptions(
            name='entitytoworkrel',
            options={'managed': True, 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='historicalentitytoentityrel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Affiliation'},
        ),
        migrations.AlterModelOptions(
            name='historicalentitytoworkrel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Role'},
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='relationship',
            field=models.CharField(choices=[('Composición', 'Composición'), ('Lectura en voz alta', 'Lectura en voz alta'), ('Interpretación musical', 'Interpretación musical'), ('Ingeniería de sonido', 'Ingeniería de sonido'), ('Producción', 'Producción'), ('Dirección', 'Dirección'), ('Post-producción', 'Post-producción'), ('Auxiliar de sonido', 'Auxiliar de sonido'), ('Contribuidor', 'Contribuidor'), ('Publicador', 'Publicador'), ('Traducción', 'Traducción')], default='Lectura en voz alta', max_length=256, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='relationship',
            field=models.CharField(choices=[('Composición', 'Composición'), ('Lectura en voz alta', 'Lectura en voz alta'), ('Interpretación musical', 'Interpretación musical'), ('Ingeniería de sonido', 'Ingeniería de sonido'), ('Producción', 'Producción'), ('Dirección', 'Dirección'), ('Post-producción', 'Post-producción'), ('Auxiliar de sonido', 'Auxiliar de sonido'), ('Contribuidor', 'Contribuidor'), ('Publicador', 'Publicador'), ('Traducción', 'Traducción')], default='Lectura en voz alta', max_length=256, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='work',
            name='in_collection',
            field=models.ForeignKey(blank=True, db_column='in_collection', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.WorkCollection', verbose_name='Collection that this recording is a part of'),
        ),
    ]
