# Generated by Django 2.2.10 on 2020-04-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_blank_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwork',
            name='copyright_version',
            field=models.CharField(default='4.0', max_length=16, verbose_name='License version'),
        ),
        migrations.AddField(
            model_name='work',
            name='copyright_version',
            field=models.CharField(default='4.0', max_length=16, verbose_name='License version'),
        ),

        migrations.RunSQL("""UPDATE poet_work SET copyright_version = '4.0' WHERE copyright ILIKE '%CC%'"""),
    ]
