# Generated by Django 2.0.6 on 2018-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0003_auto_20180722_1429'),
    ]

    operations = [

        migrations.AddField(
            model_name='grupo',
            name='city_of_origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='country_of_origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='subdivision_of_origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='city_of_death',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='city_of_origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='country_of_death',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='country_of_origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='subdivision_of_death',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='subdivision_of_origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pistason',
            name='city_of_origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pistason',
            name='country_of_origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pistason',
            name='subdivision_of_origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pistason',
            name='medio',
            field=models.CharField(choices=[('Digital', 'Digital'), ('CD', 'CD'), ('Cinta', 'Tape'), ('Vinilo', 'Vinyl')], default='Digital', max_length=32),
        ),
        migrations.AlterField(
            model_name='serie',
            name='coment',
            field=models.TextField(blank=True, db_column='coment', null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serie',
            name='nom',
            field=models.TextField(db_column='nom'),
        ),

        migrations.RunSQL('ALTER TABLE archivo RENAME COLUMN nom_archivo TO nom;'),
        migrations.RunSQL('ALTER TABLE composicion RENAME COLUMN nom_tit TO nom;')

    ]
