# Generated by Django 2.0.6 on 2018-08-20 01:55
# Data migration from first model to second.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0008_auto_20180820_0152'),
    ]

    operations = [
    ]
