# Generated by Django 2.1.1 on 2018-09-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0008_model_refactor'),
    ]

    operations = [
        migrations.RunSQL("""ALTER TABLE poet_entity ALTER COLUMN tags SET DEFAULT array[]::varchar[]"""),
        migrations.RunSQL("""ALTER TABLE poet_work ALTER COLUMN tags SET DEFAULT array[]::varchar[]"""),

        migrations.RunSQL("""
        CREATE OR REPLACE FUNCTION quote(IN word VARCHAR, OUT maybe_word text) AS $body$
        BEGIN
            maybe_word := coalesce(nullif(concat('"', word, '"'), '""'), 'null');
        END;
        $body$
        LANGUAGE plpgsql
        IMMUTABLE;
        """),

        migrations.RunSQL("""
        CREATE OR REPLACE FUNCTION transform_date(IN str_date VARCHAR, OUT start_date date, OUT end_date date) AS $body$
        BEGIN
            IF (str_date ~ '^\d\d\d\d-\d\d-\d\d$') THEN
              start_date := to_date(str_date, 'YYYY-MM-DD');
              end_date := to_date(str_date, 'YYYY-MM-DD');
            ELSIF (str_date ~ '^\d\d\d\d$') THEN
              start_date := to_date(str_date, 'YYYY');
              end_date := (to_date(str_date, 'YYYY') + interval '1 year') :: date;
            ELSIF (str_date ~ '^\d\d\d\d-\d\d$') THEN
              start_date := to_date(str_date, 'YYYY-MM');
              end_date := (to_date(str_date, 'YYYY-MM') + interval '1 month') :: date;
            ELSE
              start_date := NULL;
              end_date := NULL;
            END IF;
        END;
        $body$
        LANGUAGE plpgsql
        IMMUTABLE;
        """),
    ]
