# Generated by Django 2.1.2 on 2018-10-22 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0010_util_funcs'),
    ]

    operations = [
        migrations.RenameField('EntityToWorkRel', 'from_model', 'from_entity'),
        migrations.RenameField('EntityToWorkRel', 'to_model', 'to_work'),
        migrations.RenameField('EntityToWorkRel', 'comments', 'commentary'),
        migrations.RenameField('EntityToEntityRel', 'from_model', 'from_entity'),
        migrations.RenameField('EntityToEntityRel', 'to_model', 'to_entity'),
        migrations.RenameField('EntityToEntityRel', 'comment', 'commentary'),
        migrations.RenameField('WorkToWorkRel', 'from_model', 'from_work'),
        migrations.RenameField('WorkToWorkRel', 'to_model', 'to_work'),
        migrations.RenameField('WorkToWorkRel', 'comments', 'commentary'),
        migrations.RenameField('Work', 'comments', 'commentary'),
        migrations.RenameField('Entity', 'comments', 'commentary'),
        migrations.RenameField(
            model_name='historicalentitytoentityrel',
            old_name='from_model',
            new_name='from_entity',
        ),
        migrations.RenameField(
            model_name='historicalentitytoentityrel',
            old_name='to_model',
            new_name='to_entity',
        ),
        migrations.RenameField(
            model_name='historicalworktoworkrel',
            old_name='from_model',
            new_name='from_work',
        ),
        migrations.RenameField(
            model_name='historicalworktoworkrel',
            old_name='to_model',
            new_name='to_work',
        ),
        migrations.RemoveField(
            model_name='historicalentitytoworkrel',
            name='from_model',
        ),
        migrations.RemoveField(
            model_name='historicalentitytoworkrel',
            name='to_model',
        ),
        migrations.AddField(
            model_name='historicalentitytoworkrel',
            name='from_entity',
            field=models.ForeignKey(blank=True, db_column='from_entity', db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='poet.Entity'),
        ),
        migrations.AddField(
            model_name='historicalentitytoworkrel',
            name='to_work',
            field=models.ForeignKey(blank=True, db_column='to_work', db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='poet.Work'),
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='from_entity',
            field=models.ForeignKey(db_column='from_entity', on_delete=django.db.models.deletion.CASCADE,
                                    to='poet.Entity'),
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='to_work',
            field=models.ForeignKey(db_column='to_work', on_delete=django.db.models.deletion.CASCADE, to='poet.Work'),
        ),

        migrations.RunSQL("ALTER TABLE idioma RENAME COLUMN idioma_id TO id"),
        migrations.RunSQL("ALTER TABLE idioma RENAME COLUMN nom_idioma TO nom"),

        migrations.RunSQL("ALTER TABLE tema RENAME COLUMN tema_id TO id"),
        migrations.RunSQL("ALTER TABLE tema RENAME COLUMN nom_tema TO nom"),

        migrations.RunSQL("ALTER TABLE genero_musical RENAME COLUMN gen_mus_id TO id"),
        migrations.RunSQL("ALTER TABLE genero_musical RENAME COLUMN nom_gen_mus TO nom"),
        migrations.RunSQL("ALTER TABLE genero_musical RENAME COLUMN coment_gen_mus TO coment"),

        migrations.RunSQL("ALTER TABLE album RENAME COLUMN album_id TO id"),
        migrations.RunSQL("ALTER TABLE album RENAME COLUMN nom_album TO nom"),

        migrations.RunSQL("ALTER TABLE serie RENAME COLUMN serie_id TO id"),
        migrations.RunSQL("ALTER TABLE serie RENAME COLUMN nom_serie TO nom"),
        migrations.RunSQL("ALTER TABLE serie RENAME COLUMN coment_serie TO coment"),

        migrations.RunSQL("ALTER TABLE familia_instrumento RENAME COLUMN familia_instr_id TO id"),
        migrations.RunSQL("ALTER TABLE familia_instrumento RENAME COLUMN nom_familia_instr TO nom"),

        migrations.RunSQL("ALTER TABLE instrumento RENAME COLUMN instrumento_id TO id"),
        migrations.RunSQL("ALTER TABLE instrumento RENAME COLUMN nom_inst TO nom"),
        migrations.RunSQL("ALTER TABLE instrumento RENAME COLUMN instrumento_comentario TO coment"),

        migrations.RunSQL("ALTER TABLE archivo RENAME COLUMN archivo_id TO id"),

        migrations.RunSQL("ALTER TABLE cobertura RENAME COLUMN cobertura_id TO id"),
        migrations.RunSQL("ALTER TABLE cobertura_licencia RENAME COLUMN cobertura_lic_id TO id"),

        migrations.RunSQL("ALTER TABLE composicion RENAME COLUMN composicion_id TO id"),
        migrations.RunSQL("ALTER TABLE composicion RENAME COLUMN nom_tit TO nom"),
        migrations.RunSQL("ALTER TABLE archivo RENAME COLUMN nom_archivo TO nom"),

    ]
