# Generated by Django 2.1.2 on 2018-11-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0019_work_relationship_choices'),
    ]

    operations = [
        migrations.RunSQL("""
        UPDATE poet_entity SET 
            address = additional_data->>'Dirección',
            email_address = additional_data->>'Email',
            website = additional_data->>'Sitio Web',   
            start_date = additional_data->>'Nacimiento',
            end_date = additional_data->>'Fallecimiento';
        """),

        migrations.RunSQL("""
        UPDATE poet_entity SET 
            start_date = CASE
                            WHEN additional_data ? 'Inicio' THEN additional_data->>'Inicio' 
                            ELSE start_date
                         END,
            end_date = CASE
                            WHEN additional_data ? 'Finalización' THEN additional_data->>'Finalización'
                            ELSE end_date
                         END;    
        """),

        migrations.RunSQL("""
        UPDATE poet_entity 
        SET additional_data = 
        additional_data - '{Dirección,Email,Sitio Web,Nacimiento,Inicio,Fallecimiento,Finalización}'::text[]
        """),

        migrations.RunSQL("""        
        UPDATE poet_work SET 
              media_of_origin = additional_data->>'Medios de origen',
              date_contributed = additional_data->>'Contribución',
              date_digitalized = additional_data->>'Digitalizado',
              date_recorded = additional_data->>'Grabación',
              languages = (SELECT array_agg(j) FROM jsonb_array_elements_text(additional_data->'Idiomas') j),
              date_published = additional_data->>'Publicado';
        """),
        migrations.RunSQL("""        
        UPDATE poet_work_to_work_rel rel 
        SET track_order = (pw.additional_data->>'Número de pista')::int
        FROM poet_work pw
        WHERE rel.to_work = pw.id
        AND pw.additional_data ? 'Número de pista'
        """),

        migrations.RunSQL("""
        UPDATE poet_work
        SET additional_data = 
        additional_data - '{Medios de origen,Contribución,Digitalizado,Grabación,Idiomas,Publicado,Número de pista}'::text[]
        """),
    ]
